### ISSUE TITLE
Error running make on macOS Mojave

### ISSUE THREAD

**Issue by liamtoney** [chetzer-ncpa/ncpaprop#16]
I'm trying to install on macOS Mojave 10.14.2, and I get an error which is similar to that reported in #11. I was able to successfully run `./configure` but upon running `make` I receive: 
```console
...
Completed building libraries
=========================================
Now to install the library do:
make SLEPC_DIR=/Users/ldtoney/Downloads/ncpaprop-master PETSC_DIR=/Users/ldtoney/Downloads/ncpaprop-master/src/extern/petsc-3.2-p5/ PETSC_ARCH=arch-installed-petsc install
=========================================
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/ldtoney/Downloads/ncpaprop-master/src/extern/slepc-3.2-p3/ PETSC_ARCH=arch-darwin18.2.0-c-debug SLEPC_DIR=/Users/ldtoney/Downloads/ncpaprop-master/src/extern/slepc-3.2-p3/ PETSC_DIR=/Users/ldtoney/Downloads/ncpaprop-master/src/extern/petsc-3.2-p5/ test
Running test examples to verify correct installation
Using SLEPC_DIR=/Users/ldtoney/Downloads/ncpaprop-master/src/extern/slepc-3.2-p3/, PETSC_DIR=/Users/ldtoney/Downloads/ncpaprop-master/src/extern/petsc-3.2-p5/ and PETSC_ARCH=arch-darwin18.2.0-c-debug
C/C++ example src/eps/examples/tests/test10 run successfully with 1 MPI process
Possible error running Fortran src/eps/examples/tests/test7f with 1 MPI process
 All requested eigenvalues computed up to the required tolerance:
     3.98974, 3.95906, 3.90828, 3.83792


1-D Laplacian Eigenproblem, n = 30 (Fortran)
 Solution method: krylovschur                                                                     
 Number of requested eigenvalues: 4
make[4]: *** [testtest7f] Error 1
make[3]: *** [test_build] Error 2
touch .slepc-real
cd slepc-3.2-p3 ; \
	export PETSC_ARCH=arch-darwin18.2.0-c-complex ; \
	export PETSC_DIR=/Users/ldtoney/Downloads/ncpaprop-master/src/extern/petsc-3.2-p5/ ; \
	./configure
Checking environment...
Checking PETSc installation...
ERROR: Unable to link with PETSc
ERROR: See "arch-darwin18.2.0-c-complex/conf/configure.log" file for details
make[1]: *** [.slepc-complex] Error 1
make: *** [extern] Error 2
```
I've attached [`arch-darwin18.2.0-c-complex/conf/configure.log`](https://github.com/chetzer-ncpa/ncpaprop/files/2747898/configure.log) in case it's useful.

From #12 it sounds like this is already a known issue.

**Comment by dtailpied** [comment]
Hello,
I have also tried to install on Mac Mojave 10.14. However I got issue with the ./configure step, and did not reach the make step. The system couldn't find the libraries (fftw) even though I had followed the process to install them. 
In case you may have a clue to fix that?
Thank you.

**Comment by chetzer-ncpa** [comment]
This worked for another user (he was using Ubuntu Linux):

First thing I would try would be to locate the directory where it lives and add it to the linker search path as an option to the configure script.  You can probably do this with either 'locate libfftw3.so' or 'find / -name libfftw3.so'.  Then run configure with LDFLAGS="${LDFLAGS}:/path/to/library"
________________________________

**Comment by chetzer-ncpa** [comment]
Sorry for the delay.  The configuration process has been completely rewritten and updated.  Please see the new manual for details, but in short, you can try to run:

./configure --with-localpetsc

to have the build process download and install PETSc/SLEPc for you while it's setting things up.

**Comment by liamtoney** [comment]
`make` runs successfully with the new edits, thanks!
